services:
  api:
    container_name: car-rental-api
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - CCACHE_DIR=/home/user/lab2/.ccache
      - CORES_DIR=/cores
      - PREFIX=${PREFIX:-~/.local}
      - SHELL=/bin/bash
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - '${SERVER_PORT}:8080'
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp=unconfined
    volumes:
      - ccache-volume:/home/user/lab2/.ccache
      - cores-volume:/cores
    working_dir: /home/user/lab2
    user: user
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:8080/ping']
      interval: 10s
      timeout: 3s
      retries: 5
      start_period: 10s
    logging:
      driver: 'local'
      options:
        max-size: '10m'
        max-file: '3'
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - api_network

  postgres:
    image: postgres:latest
    container_name: car-rental-db
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - '${POSTGRES_PORT}:5432'
    volumes:
      - postgres-data:/var/lib/postgresql
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}']
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - api_network

volumes:
  postgres-data:
  ccache-volume:
  cores-volume:

networks:
  api_network:
    driver: bridge