services:
  api:
    container_name: car-rental-api
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - CCACHE_DIR=/home/user/lab2/.ccache
      - CORES_DIR=/cores
      - PREFIX=${PREFIX:-~/.local}
      - SHELL=/bin/bash
      - MONGO_URI=${MONGO_URI}
    ports:
      - '${SERVER_PORT}:8080'
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp=unconfined
    volumes:
      - ccache-volume:/home/user/lab2/.ccache
      - cores-volume:/cores
    working_dir: /home/user/lab2
    user: user
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:8080/ping']
      interval: 10s
      timeout: 3s
      retries: 5
      start_period: 10s
    logging:
      driver: 'local'
      options:
        max-size: '10m'
        max-file: '3'
    depends_on:
      mongo:
        condition: service_healthy
    networks:
      - api_network

  mongo:
    image: mongo:7.0
    container_name: car-rental-mongodb
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_DB}
    ports:
      - '${MONGO_PORT}:27017'
    volumes:
      - mongodb-data:/data/db
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    healthcheck:
      test: ['CMD', 'mongosh', '--eval', "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - api_network

volumes:
  mongodb-data:
  ccache-volume:
  cores-volume:

networks:
  api_network:
    driver: bridge
