components_manager:
  task_processors:
    main-task-processor:
      worker_threads: $worker-threads

    fs-task-processor:
      worker_threads: $worker-fs-threads

  default_task_processor: main-task-processor

  components:
    server:
      listener:
        port: $server-port
        task_processor: main-task-processor

    logging:
      fs-task-processor: fs-task-processor
      loggers:
        default:
          file_path: '@stderr'
          level: $logger-level
          overflow_behavior: discard

    dynamic-config:
      defaults:
        HTTP_CLIENT_CONNECTION_POOL_SIZE: 1000
      fs-task-processor: fs-task-processor
      load-enabled: true
      updates-enabled: false

    testsuite-support: {}

    congestion-control:

    http-client:
    http-client-core:
      load-enabled: $is_testing
      fs-task-processor: fs-task-processor

    dns-client:
      fs-task-processor: fs-task-processor

    tests-control:
      load-enabled: $is-testing
      path: /tests/{action}
      method: POST
      task_processor: main-task-processor

    handler-ping:
      path: /ping
      method: GET
      task_processor: main-task-processor
      throttling_enabled: false
      url_trailing_slash: strict-match

    # MongoDB
    mongo-storage-component:
      # prod
      mongo-uri: mongodb://mongo:mongo@mongo:27017/car_rental?authSource=admin
      # local
      # mongo-uri: mongodb://mongo:mongo@ip:27017/car_rental?authSource=admin
    # MongoDB

    # User
    HandlerCreateUser:
      path: /api/v1/users
      method: POST
      task_processor: main-task-processor

    HandlerGetUserByLogin:
      path: /api/v1/users/by-login/{login}
      method: GET
      auth:
        types:
          - jwt-auth
      task_processor: main-task-processor
    # User

    # Auth
    HandlerLogin:
      path: /api/v1/users/login
      method: POST
      task_processor: main-task-processor

    jwt-auth-component:
      load-enabled: true
      private_key: 'private_key'
      issuer: 'my-issuer'
      audience: 'my-audience'
    # Auth

    # Car
    HandlerCreateCar:
      path: /api/v1/cars
      method: POST
      auth:
        types:
          - jwt-auth
      task_processor: main-task-processor

    HandlerGetAvailableCars:
      path: /api/v1/cars/available
      method: GET
      auth:
        types:
          - jwt-auth
      task_processor: main-task-processor

    HandlerGetCarsByClass:
      path: /api/v1/cars/class/{car_class}
      method: GET
      auth:
        types:
          - jwt-auth
      task_processor: main-task-processor
    # Car

    # Rentals
    HandlerCreateRental:
      path: /api/v1/rentals
      method: POST
      auth:
        types:
          - jwt-auth
      task_processor: main-task-processor
    # Rentals
